# Generated by Django 4.1 on 2022-09-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('adress', models.CharField(blank=True, max_length=200)),
                ('resume', models.FileField(blank=True, upload_to='resumes/')),
                ('niveau_etudes', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('service', models.CharField(max_length=30)),
                ('telephone', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('appel_telephonique', models.BooleanField(default=False)),
                ('piece_jointe', models.FileField(blank=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type_contrat', models.CharField(max_length=100)),
                ('salaire', models.IntegerField(blank=True, null=True)),
                ('entreprise', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('type_partenariat', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('appel_telephonique', models.BooleanField(default=False)),
                ('date_crenaux', models.DateTimeField(blank=True, null=True)),
                ('piece_jointe', models.FileField(blank=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Recruteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('entreprise', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=200)),
                ('needed_profile', models.CharField(blank=True, max_length=200)),
                ('crenaux_proposé', models.DateTimeField(blank=True, null=True)),
                ('appel_telephonique', models.BooleanField(default=False)),
                ('piece_jointe', models.FileField(blank=True, upload_to='documents/')),
            ],
        ),
    ]
